config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    # Concerns
    concern :photos do
        resources :photos, only: [:index, :new, :create]
    end

    concern :reviews do
        resources :reviews, only: [:index, :new, :create]
    end

    concern :checkins do
        resources :checkins, only: [:index, :new, :create]
    end

    concern :ads do
        resources :ads, only: [:index, :new, :create]
    end

    concern :user_cart_relations do
        resources :user_cart_relations, path: "subscribers", only: [:index, :new, :create]
    end

    concern :cart_tag_relations do
        resources :cart_tag_relations, path: "tags", only: [:index, :new, :create]
    end

    concern :cart_category_relations do
        resources :cart_category_relations, path: "categories", only: [:index, :new, :create]
    end

    concern :notes do
        resources :notes, only: [:index, :new, :create]
    end

    concern :hours do
        resources :hours, only: [:index, :new, :create]
    end

    concern :data do
        get :data, on: :collection
    end

    concern :search do
        get :search, on: :collection
    end

    concern :cart_concerns do
        get :claim, on: :member
        get :mark_as_moved, on: :member
    end

    # Collection routes
    devise_for :users, controllers: {:registrations => "users/registrations",
        :sessions => "users/sessions"}

    devise_for :owners, controllers: {:registrations => "owners/registrations",
        :sessions => "owners/sessions"}

    # Quickfix: devise omniauth routes do not support dynamic segments
    devise_scope :user do
        get "/login" => "users/sessions#new"
        delete "/logout" => "users/sessions#destroy"
        get "/register" => "users/registrations#new"

        match "/users/auth/:provider",
            constraints: { provider: /google_oauth2|facebook/ },
            to: "users/omniauth_callbacks#passthru",
            as: :omniauth_authorize,
            via: [:get, :post]
        match "/users/auth/:action/callback",
            constraints: { action: /google_oauth2|facebook/ },
            to: "users/omniauth_callbacks",
            as: :omniauth_callback,
            via: [:get, :post]
    end

    # User routes
    resources :users, concerns: [:photos, :reviews, :checkins, :data, :search]
    get "/account" => "users#show", as: :account

    resources :owners, concerns: [:data] do
        resources :carts, only: [:index, :new, :create]
    end

    # Cart routes
    resources :carts, concerns: [:photos, :reviews, :checkins, :hours, :data, :search,
            :cart_concerns, :ads, :user_cart_relations, :cart_tag_relations,
            :cart_category_relations] do
        member do
            resource :menu do
                resources :menu_items, path: "items", only: [:index, :new, :create]
            end
        end
    end

    # Other public routes
    resources :photos, concerns: [:data]

    resources :reviews, only: [:show, :edit, :update, :destroy],
        concerns: [:data, :search]

    resources :menu_items, only: [:show, :edit, :update, :destroy],
        concerns: [:data, :notes]

    resources :hours, only: [:show, :edit, :update, :destroy],
        concerns: [:data]

    resources :tags, concerns: [:data]

    resources :categories, concerns: [:data]

    # Private routes
    resources :ads, only: [:show, :edit, :update, :destroy],
        concerns: [:data], path: "_ads"

    resources :ad_types, concerns: [:data], path: "_ad_types"

    resources :checkins, only: [:show, :edit, :update, :destroy],
        concerns: [:data, :search], path: "_checkins"

    resources :notes, only: [:show, :edit, :update, :destroy],
        concerns: [:data], path: "_notes"

    resources :user_cart_relations, only: [:show, :edit, :update, :destroy],
        concerns: [:data], path: "_cart_associations"

    resources :cart_tag_relations, only: [:show, :edit, :update, :destroy],
        concerns: [:data], path: "_tag_instances"

    resources :cart_category_relations, only: [:show, :edit, :update, :destroy],
        concerns: [:data], path: "_category_instances"

    resources :search_lines, concerns: [:data], path: "_search_lines"

    resources :clickthroughs, concerns: [:data], path: "_clickthroughs"

    namespace :mobile do
        devise_scope :user do
            post 'sessions' => 'sessions#create', :as => 'mobile_login'
            delete 'sessions' => 'sessions#destroy', :as => 'mobile_logout'
            post 'registrations' => 'registrations#create', :as => 'mobile_register'
        end

        devise_scope :owner do
            post 'owners/sessions' => 'sessions#create', :as => 'mobile_owner_login'
            delete 'owners/sessions' => 'sessions#destroy', :as => 'mobile_owner_logout'
            post 'owners/registrations' => 'registrations#create', :as => 'mobile_owner_register'
        end
    end

    # Search
    get "/search" => "search#index", as: :search

    # Root page
    root to: "home#index", as: :home
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    # home page
    def index
        # get ads
        # get suggested carts if user is logged in
        # get suggested ghosts
        # get news items from an external blog / cms that we have
    end

    # list of carts and tags
    # ADD ROUTE
    def identifiers
        # get carts
        # get tags
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
-content_for :head do
  =javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyDeTwOMn3ZRwUcETE8wB2zxTVR-Dznbgv0"
  =javascript_include_tag "gmaps.js"

.poster.poster-top.carousel.slide{speed: "0.2"}
  .fill
    .banner
      %span Cartwheels

%nav#tab-bar.navbar.navbar-inverse{role: "navigation"}
  .container
    / Collect the nav links, forms, and other content for toggling
    .navbar-collapse.collapse
      %ul.nav.navbar-nav.navbar-left
        -if not user_signed_in? and not owner_signed_in?
          .login-link
            =link_to "Sign Up", register_path
          .login-link
            =link_to "Log In", login_path
      %ul.nav.navbar-nav.navbar-center.tab-list
        %li.active{"data-target" => "#main-content"}
          %a{href: "#about"} Map
        %li{"data-target" => "#about-content"}
          %a{href: "#about"} About
      %ul.nav.navbar-nav.navbar-right
        %a.navbar-brand{href: "https://www.facebook.com/cartwheelsUS"}
          =image_tag("fb-icon.png")
        %a.navbar-brand{href: "http://twitter.com"}
          =image_tag("tw-icon.png")
        %a.navbar-brand{href: "http://plus.google.com"}
          =image_tag("gp-icon.png")

#main-content.content-section
  #map-header.row
    .col-lg-1.col-md-1.col-sm-1.col-xs-1
    .col-lg-4.col-md-4.col-sm-4.col-xs-4
      .row-header Find Carts In Your Area
  #map-container.row
    #map-input
      %form.search-form
        .input-block
          %input.gmaps-input{name: "tq", placeholder: "Halal Guys, wafels and dinges, breakfast"}
          %input.gmaps-input.location-input{name: "lq", placeholder: "456 allen, brooklyn, 10282"}
        %button.gmaps-button.btn.btn-primary{type: "submit"}
          =image_tag("search.png")
        %button.gmaps-button.btn.btn-primary.more{type: "submit"}
          %span.glyphicon.glyphicon-refresh
    #map-tags
      .tags-header
        %a{href: "#"} Search For

      .form-group
        .checkbox.tag
          %label{"data-category" => "all"}
            %input{type: "checkbox", checked: ""} All
        -Category.most_popular(6).each do |cat|
          .checkbox.tag
            %label{"data-category" => cat.name}
              %input{type: "checkbox"}
                =cat.name
    #map-div

    %footer.row
      .row
        .col-lg-12
          %p Copyright © Cartwheels 2014


#about-content.content-section
  .poster.other.poster-top-middle.carousel.slide{speed: "0.2"}
    .fill

  .poster.other.poster-middle-one.carousel.slide{speed: "0.28"}
    .fill

  .poster.other.poster-middle-two.carousel.slide{speed: "0.3"}
    .fill

  .poster.other.poster-bottom-middle.carousel.slide{speed: "0.3"}
    .fill

  .poster.other.poster-bottom.carousel.slide{speed: "0.25"}
    .fill

  #content
    .section
      .section-header Background
      .section-content
        New York City, the vast, metropolitan expanse of concrete and steel that houses over 8 million inhabitants, sustains an immensely unique and multi-faceted culture. Mobile food vendors, including breakfast carts, food trucks, fruit stands, “green carts,” and even taco carts pervade this city, ingraining themselves deeply in the lives and routines of hungry New Yorkers. They populate centers of traffic on NY's busiest street corners, because that's how owners earn their money. Vending everything from lobsters to waffles to pastries to fresh fruit, these vendors are an important and burgeoning part of our culture. Our mission at Cartwheels is to invigorate and ameliorate the mobile food vending space. 
    .section
      .section-header The Problem
      .section-content
        Despite their pervasiveness in the urban landscape, there is little shared market data – such as geographic and product preferences of consumers, market pricing, and vendor performance measurements – for the broad category of mobile food vending providers in our city.  
        %br
        %br
        The recent popularity of food trucks has provided some performance transparency through on-line restaurant rating systems, however, the vast majority of food vendors – including regular food carts and the new (launched in 2008) green carts – are unknown quantities to consumers and public policy advocates.
        %br
        %br
        Not only can a food vendor of a particular type be hard to find, but, there is really no access to market information for consumers on pricing and quality.  On the supply side, cart owners themselves may not know what consumers want.  Regulators for their part may be able to achieve public policy goals if more market data were available.
    .section
      .section-header The Cartwheels Solution
      .section-content
        %ul
          %li
            We provide New Yorkers with instant maps of nearby carts differentiated by the products they sell through out web and mobile applications. 
          %li
            We not only allow consumers to rate and review food carts, but also allow them to report health violations on our applications - talk about accountability! 
          %li
            We facilitate communication between cart owners, consumers and potential policy-makers.  With market and performance data more readily available, cart owners can update menus items to meet popular demand, advertise their carts to attract more consumers based on price or geography, and offer specials and consumer loyalty programs. Not only do we increase accountability, but we also improve the customer experience in the mobile food vending space. 
          %li
            By providing policy makers with key market analysis of the outdoor mobile food vending space, we allow them to shape more effective policies regarding the number of carts permitted in each area.
    .section
      .section-header We ♥ small business
      .section-content
        %ul
          %li
            By driving traffic to high performing food vendors, including green carts and regular carts that serve healthy food choices, Cartwheels helps these small businesses generate revenue. 
          %li
            By facilitating communication between cart owners and consumers, we increase revenues for carts. Owners can purchase premium ads on our site and attract a recurring customer base through consumer loyalty programs. 
    .section
      .section-header We ♥ new york
      .section-content
        %ul
          %li
            NYC Department of Health and other public policy advocates will have more information about consumer behavior in the food cart space.
          %li
            Because of Cartwheels, there is more transparency for consumers looking to find a particular type of food or specific vendor –  citigoers can find food vendors near them with a click of a button. 
          %li
            Consumers get to buy healthier, tastier food from the carts they enjoy mostly by reading cart reviews. 
          %li
            Consumers can subscribe to carts, receive special offers, and participate in loyalty programs. 
          %li
            On top of these things, our review system will create greater accountability for food quality and cleanliness among food vendors. 

    .section.last
      .section-header About us
      .section-content
        %ul
          %li
            Named the #1 best high school app by the MIT Media Lab 
          %li
            Named the #2 best new app idea globally by the Institute for Electrical and Electronic Engineers (IEEE). 
          %li
            Endorsed by NYC Venture Capitalist Fred Wilson and staff at CBS Local.
          %li
            Featured in YahooNews, MarketWatch, NBC, and Fox.  
        .bio
          =image_tag(asset_path("ben.jpg"))
          .text
            .name
              Benjamin Attal
            .title
              Co-Founder and Chief Executive Officer
        .bio
          =image_tag(asset_path("jack.jpg"))
          .text
            .name
              Jack Cahn
            .title
              Co-Founder and President
        .bio
          =image_tag(asset_path("david.jpg"))
          .text
            .name
              David Cahn
            .title
              Chief Financial Officer
        .bio
          =image_tag(asset_path("will.jpg"))
          .text
            .name
              Will Field-Thompson
            .title
              iOS Lead
        .bio
          =image_tag(asset_path("eric.jpg"))
          .text
            .name
              Eric Chen
            .title
              Android Lead
        .bio
          =image_tag(asset_path("reda.jpg"))
          .text
            .name
              Reda Lamniji
            .title
              Content Expert