config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    # Concerns
    concern :photos do
        resources :photos, only: [:index, :new, :create]
    end

    concern :reviews do
        resources :reviews, only: [:index, :new, :create]
    end

    concern :checkins do
        resources :checkins, only: [:index, :new, :create]
    end

    concern :ads do
        resources :ads, only: [:index, :new, :create]
    end

    concern :user_cart_relations do
        resources :user_cart_relations, path: "subscribers", only: [:index, :new, :create]
    end

    concern :cart_tag_relations do
        resources :cart_tag_relations, path: "tags", only: [:index, :new, :create]
    end

    concern :cart_category_relations do
        resources :cart_category_relations, path: "categories", only: [:index, :new, :create]
    end

    concern :notes do
        resources :notes, only: [:index, :new, :create]
    end

    concern :hours do
        resources :hours, only: [:index, :new, :create]
    end

    concern :data do
        get :data, on: :collection
    end

    concern :search do
        get :search, on: :collection
    end

    concern :cart_concerns do
        get :claim, on: :member
        get :mark_as_moved, on: :member
    end

    # Collection routes
    devise_for :users, controllers: {:registrations => "users/registrations",
        :sessions => "users/sessions"}

    devise_for :owners, controllers: {:registrations => "owners/registrations",
        :sessions => "owners/sessions"}

    # Quickfix: devise omniauth routes do not support dynamic segments
    devise_scope :user do
        get "/login" => "users/sessions#new"
        delete "/logout" => "users/sessions#destroy"
        get "/register" => "users/registrations#new"

        match "/users/auth/:provider",
            constraints: { provider: /google_oauth2|facebook/ },
            to: "users/omniauth_callbacks#passthru",
            as: :omniauth_authorize,
            via: [:get, :post]
        match "/users/auth/:action/callback",
            constraints: { action: /google_oauth2|facebook/ },
            to: "users/omniauth_callbacks",
            as: :omniauth_callback,
            via: [:get, :post]
    end

    # User routes
    resources :users, concerns: [:photos, :reviews, :checkins, :data, :search]
    get "/account" => "users#show", as: :account

    resources :owners, concerns: [:data] do
        resources :carts, only: [:index, :new, :create]
    end

    # Cart routes
    resources :carts, concerns: [:photos, :reviews, :checkins, :hours, :data, :search,
            :cart_concerns, :ads, :user_cart_relations, :cart_tag_relations,
            :cart_category_relations] do
        member do
            resource :menu do
                resources :menu_items, path: "items", only: [:index, :new, :create]
            end
        end
    end

    # Other public routes
    resources :photos, concerns: [:data]

    resources :reviews, only: [:show, :edit, :update, :destroy],
        concerns: [:data, :search]

    resources :menu_items, only: [:show, :edit, :update, :destroy],
        concerns: [:data, :notes]

    resources :hours, only: [:show, :edit, :update, :destroy],
        concerns: [:data]

    resources :tags, concerns: [:data]

    resources :categories, concerns: [:data]

    # Private routes
    resources :ads, only: [:show, :edit, :update, :destroy],
        concerns: [:data], path: "_ads"

    resources :ad_types, concerns: [:data], path: "_ad_types"

    resources :checkins, only: [:show, :edit, :update, :destroy],
        concerns: [:data, :search], path: "_checkins"

    resources :notes, only: [:show, :edit, :update, :destroy],
        concerns: [:data], path: "_notes"

    resources :user_cart_relations, only: [:show, :edit, :update, :destroy],
        concerns: [:data], path: "_cart_associations"

    resources :cart_tag_relations, only: [:show, :edit, :update, :destroy],
        concerns: [:data], path: "_tag_instances"

    resources :cart_category_relations, only: [:show, :edit, :update, :destroy],
        concerns: [:data], path: "_category_instances"

    resources :search_lines, concerns: [:data], path: "_search_lines"

    resources :clickthroughs, concerns: [:data], path: "_clickthroughs"

    namespace :mobile do
        devise_scope :user do
            post 'sessions' => 'sessions#create', :as => 'mobile_login'
            delete 'sessions' => 'sessions#destroy', :as => 'mobile_logout'
            post 'registrations' => 'registrations#create', :as => 'mobile_register'
        end

        devise_scope :owner do
            post 'owners/sessions' => 'sessions#create', :as => 'mobile_owner_login'
            delete 'owners/sessions' => 'sessions#destroy', :as => 'mobile_owner_logout'
            post 'owners/registrations' => 'registrations#create', :as => 'mobile_owner_register'
        end
    end

    # Search
    get "/search" => "search#index", as: :search

    # Root page
    root to: "home#index", as: :home
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
    # GET /carts/:id
    def show
       # @cart = Cart.find(params[:id])
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    include Fetchable
    include Imageable

    skip_before_filter :authenticate_user!
    skip_before_filter :authenticate_owner!

    before_filter :authenticate_user!, only: [:new, :create, :update, :destroy,
        :mark_as_moved]
    skip_before_filter :authenticate_user!,
        :if => Proc.new { |c| current_owner != nil }

    before_filter :authenticate_owner!, only: [:new, :edit, :create, :update,
        :destroy, :claim]
    skip_before_filter :authenticate_owner!,
        :if => Proc.new { |c| current_user != nil }

    skip_before_action :set_instance
    before_action :set_instance, only: [:show, :edit, :update, :destroy,
        :claim, :mark_as_moved]

    def index
        @carts = Cart.where(created_at: (Time.now - 1.day)..Time.now)
    end

    def show
    end

    def new
        @cart = Cart.new
    end

    def edit
    end

    def create
        user = current_user
        user ||= current_owner

        @cart = Cart.new(cart_params)

        if @photo
            @cart.photos << @photo
        end

        if user_signed_in?
            @cart.user_cart_relations.build(user: user, relation_type: 0)
        else
            @cart.cart_owner_relations.build(owner: user)
        end

        if request.xhr? || remotipart_submitted?
            if @cart.save
                flash[:notice] = "Cart was successfully created."
                render "shared/concerns/form_default",
                    locals: {errors: nil, redirect_path: cart_path(@cart)},
                    status: :created
            else
                render "shared/concerns/form_default",
                    locals: {errors: @cart.errors},
                    status: :unprocessable_entity
            end
        else
            respond_to do |format|
                if @cart.save
                    flash[:notice] = "Cart was successfully created."
                    format.json { render status: :created,
                        location: carts_path,
                        :json => { :success => true }}
                    format.js { render "shared/concerns/form_default",
                        locals: {errors: nil,
                        redirect_path: last_path(current_owner)}}
                else
                    format.json { render status: :unprocessable_entity,
                        :json => { :errors => @cart.errors, :success => false }}
                    format.js {render "shared/concerns/form_default",
                        locals: {errors: @cart.errors}}
                end
            end
        end
    end

    def update
        if current_owner.in? @cart.owners or\
                (current_user and current_user.has_role? :admin)

            user = current_user
            user ||= current_owner

            if @photo
                @cart.photos << @photo
            end

            @cart.moved = false

            if request.xhr? || remotipart_submitted?
                Cart.skip_updates

                if @cart.update(cart_params)
                    Cart.set_updates

                    flash[:notice] = "Cart was successfully updated."
                    render "shared/concerns/form_default",
                        locals: {errors: nil, redirect_path: cart_path(@cart)},
                        status: :created
                else
                    Cart.set_updates

                    render "shared/concerns/form_default",
                        locals: {errors: @cart.errors},
                        status: :unprocessable_entity
                end
            else
                respond_to do |format|
                    Cart.skip_updates

                    if @cart.update(cart_params)
                        Cart.set_updates

                        format.html { redirect_to carts_path,
                            notice: 'Cart was succesfully updated.' }
                        format.json { render :show, status: :ok,
                            location: @cart,
                            :json => { :success => true }}
                        format.js { render "shared/concerns/form_default",
                            locals: {errors: nil,
                            redirect_path: last_path(current_owner)}}
                    else
                        Cart.set_updates

                        format.html { render :edit }
                        format.json { render status: :unprocessable_entity,
                            json: { :errors => @cart.errors,
                                :success => false }}
                        format.js {render "shared/concerns/form_default",
                            locals: {errors: @cart.errors}}
                    end
                end
            end
        else
            respond_to do |format|
                format.html { redirect_to @cart,
                    notice: 'You do not have permission to perform this action.'
                }
                format.json { render json: { success: false } }
            end
        end
    end

    def destroy
        respond_to do |format|
            if current_user == @cart.uploader or current_user.has_role? :admin
                @cart.destroy

                format.html { redirect_to carts_path,
                    notice: 'Cart was successfully destroyed.' }
                format.json { render json: {
                    success: true } }
            else
                format.html { redirect_to @cart,
                    notice: 'You do not have permission to perform this action.'
                }
                format.json { render json: { success: false } }
            end
        end
    end

    def search
        @carts = Cart.search(search_params["sort_by"], search_params["tq"],
                search_params["lq"], search_params["categories"],
                search_params["box"])
            .limit(search_params["limit"])
            .offset(search_params["offset"])

        render :status => 200, :json => { :success => true, :data => @carts }
    end

    def claim
        respond_to do |format|
            if not @cart.permit_number.empty? and\
                    params[:permit_number] == @cart.permit_number
                @cart.owners << current_owner

                format.html { redirect_to @cart,
                    notice: 'Cart successfully claimed.' }
                format.json { render json: { success: true } }
            else
                format.html { redirect_to last_path(current_owner),
                    notice: 'You do not have permission to perform this action.'
                }
                format.json { render json: { success: false } }
            end
        end
    end

    def mark_as_moved
        respond_to do |format|
            if @cart.update_attributes(moved: params[:moved])
                format.html { redirect_to @cart,
                    notice: 'Cart marked as moved' }
                format.json { render json: { success: true } }
            else
                format.html { redirect_to @cart, notice: 'Failed to mark cart' }
                format.json { render json: { success: false } }
            end
        end
    end

    def data_params
        params.require(:cart).permit(:id, :name, :city, :permit_number,
            :zip_code)
    end

    def search_params
        ps = params.permit(:offset, :limit, :sort_by, :tq, :lq, categories: [],
            box: [])
        defaults = {"offset" => 0, "limit" => 20, "sort_by" => "popularity",
            "categories" => [], "box" => []}
        defaults.merge(ps)
    end

    def cart_params
        params.require(:cart).permit(:name, :city, :permit_number, :lat, :lon,
            :green, :rating, :description, :twitter_handle)
    end

    private :data_params
    private :search_params
    private :cart_params
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.haml
-content_for :head do
  =javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyDeTwOMn3ZRwUcETE8wB2zxTVR-Dznbgv0"
  =javascript_include_tag "gmaps.js"

.map-form
  .map
  .map-search
    %form.search-form
      %input.form-input.location-input#address-input{name: "lq", placeholder: "Search for an address near the cart"}
      %button.hidden{type: "submit"}

  .wheels-form
    .form-header
      -if action_name == "new"
        %a{href: "#"} Submit a cart
      -else
        %a{href: "#"} Edit cart

    =form_for cart, remote: true, html: {:multipart => true, 'data-model' => 'cart'} do |f|
      .form-group
        .row
          = f.text_field :name, :class => 'form-input',
              :placeholder => 'Name of the cart.'
        .row
          .help-block

      .form-group
        .row
          = f.text_field :permit_number, :class => 'form-input',
              :placeholder => 'Permit number'
        .row
          .help-block

      .form-group
        .row
          .form-label Is this an NYC Green Cart?
        .row
          = f.radio_button :green, 1
          = label_tag(:age_false, "Yes")
          = f.radio_button :green, 2
          = label_tag(:age_false, "No")
          = f.radio_button :green, 0
          = label_tag(:age_true, "Not Sure")
        .row
          .help-block

      .form-group
        .row
          = f.text_field :twitter_handle, :class => 'form-input',
              :placeholder => 'Cart\'s twitter handle, e.g. @cartwheels'
        .row
          .help-block

      .form-group.row
        %span.btn.btn-secondary.form-btn.file-btn.login-btn
          .label
            Upload Image
          = f.file_field :image, :placeholder => 'Image', :class => 'img-input'
        = f.submit "Submit", class: "btn btn-primary form-btn"

      = f.hidden_field :lat, value: (cart.lat.nil? ? 40.7820015 : cart.lat)
      = f.hidden_field :lon, value: (cart.lon.nil? ? -73.8317032 : cart.lon)

      .form-group.row

app/views/carts/_show_cart.html.haml
.cart{id: "cart_#{cart.id}", "data-cart-id" => cart.id}
  .content
    .info.section
      .info-header
        .photo
          -if cart.photos.first
            %a{"data-toggle" => "modal", "data-target" => "#photos-modal-#{cart.id}"}
              =image_tag(cart.photos.first.image_url_large)
          -else
            =image_tag("/system/images/default.png")
        .actions
          -if cart.twitter_handle and cart.twitter_handle != ''
            .action-link
              %a.glyphicon.glyphicon-comment{href: twitter_url(cart.twitter_handle)}
              Twitter
          -if user_signed_in?
            .action-link
              %span.glyphicon.glyphicon-ok{"data-toggle" => "modal", "data-target" => "#checkins-modal-#{cart.id}"}
              Checkin
          -if user_signed_in? and not cart.moved
            .action-link.mark-as-moved
              %span.glyphicon.glyphicon-exclamation-sign
              Mark as Moved
          -if owner_signed_in? and not cart.in? current_owner.carts
            .action-link
              %span.glyphicon.glyphicon-briefcase{"data-toggle" => "modal", "data-target" => "#claim-modal-#{cart.id}"}
              Claim
          -if cart.green == 1
            .action-link
              %span.glyphicon.glyphicon-leaf
      .info-content
        .subsection
          .col-lg-4.col-md-4.col-sm-4.col-xs-4
            .rating{"data-score" => cart.rating }
            .reviews="#{cart.reviews.count} reviews"
            .name=cart.name
          .col-lg-4.col-md-4.col-sm-4.col-xs-4
            .categories
              -if cart.categories.first
                -cart.categories[0..2].each do |item|
                  .item
                    =link_to item.name, "#"
            -if cart.categories.count > 3
              =link_to "#{cart.categories[3..-1].count} more", "#", {"data-toggle" => "modal", "data-target" => "#categories-modal-#{cart.id}", :class => "more-link"}
            -else
              %a{href: "#", "data-toggle" => "modal", "data-target" => "#categories-modal-#{cart.id}", :class => "more-link"}
                Add a category
          .col-lg-4.col-md-4.col-sm-4.col-xs-4
            .location
              %a.pop-image.pop-image-top{href: "#", "data-title" => cart.moved ? "MOVED": "Address", "data-content" => cart.moved ? "This cart has moved" : cart.address, "data-toggle" => "modal", "data-target" => "#directions-modal-#{cart.id}"}
                -if Rails.env.production?
                  = image_tag "http://maps.google.com/maps/api/staticmap?size=210x150&sensor=false&zoom=14&markers=#{cart.lat}%2C#{cart.lon}&key=#{SECRETS['google_static']}", class: "map"
                -else
                  = image_tag "http://maps.google.com/maps/api/staticmap?size=210x150&sensor=false&zoom=14&markers=#{cart.lat}%2C#{cart.lon}", class: "map"
        .subsection.hours
          .section-header
            %span.glyphicon.glyphicon-time
            Hours
          .col-lg-6.col-md-6.col-sm-6.col-xs-6
            -if cart.hours.first
              -cart.hours.order(:day).each do |item|
                .item.row
                  .col-lg-2.col-md-2.col-sm-2.col-xs-2.day=n_to_day(item.day)
                  .start.col-lg-3.col-md-3.col-sm-3.col-xs-3=n_to_time(item.start)
                  .bridge.col-lg-1.col-md-1.col-sm-1.col-xs-1 To
                  .end.col-lg-4.col-md-4.col-sm-4.col-xs-4=n_to_time(item.end)
                  -if owner_signed_in?
                    =link_to "delete", hour_path(item), method: :delete, confirm: "Are you sure you want to remove these hours?"
            -else
              .not-available.warning No hours available
          -if cart.hours.count < 7
            -if user_signed_in? or owner_signed_in?
              .col-lg-5.col-md-5.col-sm-5.col-xs-5
                .add-hours.wheels-form
                  =render partial: "hours/form", locals: {cart: cart, hour: Hour.new}
    .section
      .col-lg-4.col-md-4.col-sm-4.col-xs-4.subsection-col.menu
        .section-header
          %span.glyphicon.glyphicon-th-list
          Menu
        //Slideshow form default, list form when expands
        -if not cart.menu.nil? and cart.menu.menu_items.first
          .row
            -cart.menu.menu_items.each do |item|
              .item{id: "#{item.id}"}
                .col-lg-6.col-md-6.col-sm-6.col-xs-6
                  .photo
                    -if item.photo
                      =image_tag(item.photo.image_url_thumb)
                    -else
                      =image_tag("/system/images/default.png")
                .col-lg-6.col-md-6.col-sm-6.col-xs-6
                  .name=item.name
                  .price="$#{item.price}"
                  .destroy
                    =link_to "delete", menu_item_path(item), method: :delete, confirm: "Are you sure you want to remove this item?"

        -if user_signed_in? or owner_signed_in?
          .form-section
            =render partial: "menu_items/form", locals: {cart: cart, menu_item: MenuItem.new}

      .col-lg-8.col-md-8.col-sm-8.col-xs-8.subsection-col.reviews
        .section-header
          %span.glyphicon.glyphicon-edit
          Reviews
        -if cart.reviews.first
          -if cart.reviews.first
            -cart.reviews[0..7].each do |review|
              .item
                .rating{'data-score' => review.rating}
                .user=review.user.name
                .date=time_ago_in_words(review.updated_at) + " ago"
                .text=review.text

        -if user_signed_in? and cart.reviews.where(user: current_user).empty?
          .form-section
            =render partial: "reviews/form", locals: {cart: cart, review: Review.new}

  .modal.fade.categories-modal{id: "categories-modal-#{cart.id}", "aria-hidden" => "true", "role" => "dialog", "tabindex" => -1}
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{"data-dismiss" => "modal", type: "button"}
            %span{"aria-hidden" => "true"} ×
            %span.sr-only Close
          %h3.modal-title="Categories - #{cart.name}"
        .modal-body
          .categories
            -cart.categories.each do |item|
              .item
                -if owner_signed_in?
                  =link_to item.name, cart.cart_category_relations.where(category_id: item.id).first, method: :delete, confirm: "Are you sure you want to remove this category?"
                -else
                  =link_to item.name, "#"
          -if user_signed_in? or owner_signed_in?
            =render partial: "cart_category_relations/form", locals: {ccr: CartCategoryRelation.new, cart: cart}

  .modal.fade.directions-modal{id: "directions-modal-#{cart.id}", "aria-hidden" => "true", "role" => "dialog", "tabindex" => -1}
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{"data-dismiss" => "modal", type: "button"}
            %span{"aria-hidden" => "true"} ×
            %span.sr-only Close
          %h3.modal-title="Directions to #{cart.name}"
        .modal-body
          .directions-body
            .directions-map{id: "directions-map-#{cart.id}", "data-latitude" => cart.lat, "data-longitude" => cart.lon}
            .directions-panel{id: "directions-panel-#{cart.id}"}
              .heading Directions
              .container
          .wheels-form
            .form-group
              %form.search-form
                .row
                  %input.form-input.location-input#address{name: "lq", placeholder: "Start Address"}
                  %button.hidden{type: "submit"}

  .modal.fade.claim-modal{id: "claim-modal-#{cart.id}", "aria-hidden" => "true", "role" => "dialog", "tabindex" => -1}
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{"data-dismiss" => "modal", type: "button"}
            %span{"aria-hidden" => "true"} ×
            %span.sr-only Close
          %h3.modal-title="Claim #{cart.name}"
        .modal-body
          .wheels-form
            .form-group
              %form{action: claim_cart_path(cart)}
                .row
                  %input.form-input.location-input#address{name: "permit_number", placeholder: "Enter permit number"}
                  %button.btn.btn-primary.form-btn{type: "submit"}
                    Claim

  .modal.fade.checkins-modal{id: "checkins-modal-#{cart.id}", "aria-hidden" => "true", "role" => "dialog", "tabindex" => -1}
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{"data-dismiss" => "modal", type: "button"}
            %span{"aria-hidden" => "true"} ×
            %span.sr-only Close
          %h3.modal-title="Checkin at #{cart.name}"
        .modal-body
          -if user_signed_in?
            =render partial: "checkins/form", locals: {cart: cart, checkin: Checkin.new}

  -if cart.photos.first
    .modal.fade.photos-modal{id: "photos-modal-#{cart.id}", "aria-hidden" => "true", "role" => "dialog", "tabindex" => -1}
      .modal-dialog
        .modal-content
          .modal-header
            %button.close{"data-dismiss" => "modal", type: "button"}
              %span{"aria-hidden" => "true"} ×
              %span.sr-only Close
            %h3.modal-title="Photos for #{cart.name}"
          .modal-body
            .photos
              .carousel.slide.photos-carousel{id: "photos-carousel-#{cart.id}", "data-ride" => "carousel"}
                .carousel-inner
                  -cart.photos.each do |photo|
                    -if photo == cart.photos.first
                      .item.active
                        =image_tag(photo.image_url)
                    -else
                      .item
                        =image_tag(photo.image_url)
                %a.left.carousel-control{href: "#photos-carousel-#{cart.id}", "role" => "button", "data-slide" => "prev"}
                  %span.glyphicon.glyphicon-chevron-left
                %a.right.carousel-control{href: "#photos-carousel-#{cart.id}", "role" => "button", "data-slide" => "next"}
                  %span.glyphicon.glyphicon-chevron-right

app/views/carts/edit.html.haml
= render partial: 'form', locals: {cart: @cart}

app/views/carts/index.html.haml
-content_for :head do
  =javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyDeTwOMn3ZRwUcETE8wB2zxTVR-Dznbgv0"
  =javascript_include_tag "gmaps.js"

#heading
  %h1 Listing carts

  = link_to 'New Cart', new_cart_path, "data-no-turbolink" => true

#carts
  -@carts.each do |cart|
    =render partial: "carts/cart", locals: {cart: cart, small: true}

app/views/carts/new.html.haml
=render partial: "form", locals: {cart: @cart}

app/views/carts/show.html.haml
=render partial: "layouts/carts", locals: {carts: [@cart], small: false, tq: @tq, lq: @lq}